// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuxelJrkL8B5S08YvLxS-eHXI_p6_Gt34',
    appId: '1:542044117550:web:0ab3692b0e8a9645de5dbf',
    messagingSenderId: '542044117550',
    projectId: 'nextrade-3aba7',
    authDomain: 'nextrade-3aba7.firebaseapp.com',
    storageBucket: 'nextrade-3aba7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEL0QyZ2FPNL9Dx1yaKziCLmQrB-py8Vo',
    appId: '1:542044117550:android:e5ccc392fc7dd235de5dbf',
    messagingSenderId: '542044117550',
    projectId: 'nextrade-3aba7',
    storageBucket: 'nextrade-3aba7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNTPXZs-cOepyLUlPDrPMya585yvYIzfs',
    appId: '1:542044117550:ios:84828cb455e28121de5dbf',
    messagingSenderId: '542044117550',
    projectId: 'nextrade-3aba7',
    storageBucket: 'nextrade-3aba7.firebasestorage.app',
    iosClientId: '542044117550-ia1uo6vb4mpa65f0ehpc65eueql7h7r3.apps.googleusercontent.com',
    iosBundleId: 'com.nextrade.nextrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNTPXZs-cOepyLUlPDrPMya585yvYIzfs',
    appId: '1:542044117550:ios:84828cb455e28121de5dbf',
    messagingSenderId: '542044117550',
    projectId: 'nextrade-3aba7',
    storageBucket: 'nextrade-3aba7.firebasestorage.app',
    iosClientId: '542044117550-ia1uo6vb4mpa65f0ehpc65eueql7h7r3.apps.googleusercontent.com',
    iosBundleId: 'com.nextrade.nextrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuxelJrkL8B5S08YvLxS-eHXI_p6_Gt34',
    appId: '1:542044117550:web:b15bcdbe781a4350de5dbf',
    messagingSenderId: '542044117550',
    projectId: 'nextrade-3aba7',
    authDomain: 'nextrade-3aba7.firebaseapp.com',
    storageBucket: 'nextrade-3aba7.firebasestorage.app',
  );
}